### ISSUE TITLE
Add OAuth Login/Logout

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/ctx.do#3]

**Comment by sam-lippert** [comment]
Should this just check `req.cookies['__Session-worker.auth.providers-token']` and add a link for https://oauth.do/login and https://oauth.do/logout?

**Comment by nathanclevenger** [comment]
It’s more complex than that, because we have to store the cookies on the domain that is calling ctx.do … so we need to figure out the best architecture … probably we’ll want to have the oauth-do worker on say */login, /logout, /auth* routes so it can make and receive the callback and store the cookie on that domain
