### ISSUE TITLE
Handle writeDataPoint errors

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/ctx.do#41]
Currently very long URLs will crash ctx.do with 

```json
{
  "error": {
    "name": "TypeError",
    "message": "writeDataPoint(): Cumulative size of blobs exceeds 5120 bytes)."
  }
}
```

We need to cleanly handle/swallow that ... and probably trim URL if it's over a certain length

**Comment by sam-lippert** [comment]
https://github.com/drivly/ctx.do/commit/83ad15047e3672eef797c20b6701fd30f5083786
